apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: ecom
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingress"]
  verbs: ["create", "delete", "update"]
