apiVersion: v1
kind: Role
metadata:
  name: jenkins-role
  namespace: ecom
rules:
- apiGroup: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "update"]
- apiGroup: [""]
  resources: ["services"]
  verbs: ["create", "delete", "update"]
- apiGroup: ["networking.k8s.io"]
  resources: ["ingress"]
  verbs: ["create", "delete", "update"]
