apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
spec:
  selector:
    app: SERVICE_NAME
  ports:
    - port: SERVICE_PORT
      targetPort: SERVICE_PORT
      protocol: TCP
  type:
    ClusterIP