- name: Clone Git Repository
  hosts: all
  tasks:
  - name: Install Git
    become: yes
    package:
      name: git
      state: present

  - name: Clone repository
    git:
      repo: https://github.com/Cjay13/complete-cicd-pipeline.git
      dest: /tmp
